# Generated by Django 4.1.1 on 2022-10-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_bio',
            new_name='bio',
        ),
    ]
