# Generated by Django 4.1.1 on 2022-11-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_remove_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-shared_date', '-date_posted']},
        ),
        migrations.AlterField(
            model_name='post',
            name='shared_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
