# Generated by Django 4.1.1 on 2022-11-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_post_options_alter_post_shared_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-shared_date', '-date_posted']},
        ),
        migrations.AlterField(
            model_name='post',
            name='shared_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
