# Generated by Django 4.1.1 on 2022-11-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_alter_post_options_alter_post_shared_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted', '-shared_date']},
        ),
    ]
