# Generated by Django 4.1.1 on 2022-11-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted', '-shared_date']},
        ),
    ]
