# Generated by Django 4.1.1 on 2022-11-28 05:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0014_rename_body_messagemodel_textbody'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageModel',
            new_name='Messages',
        ),
    ]
