# Generated by Django 4.1.1 on 2022-11-28 05:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0015_rename_messagemodel_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThreadModel',
            new_name='Thread',
        ),
    ]
