# Generated by Django 4.1.1 on 2022-11-29 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='recency',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
