# Generated by Django 4.1.1 on 2022-11-29 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_notifications_recency'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='feed.thread'),
        ),
    ]
