# Generated by Django 4.1.1 on 2022-11-29 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_notifications_thread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='thread',
            new_name='message',
        ),
    ]
