# Generated by Django 4.1.1 on 2022-11-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0020_rename_thread_notifications_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='notificaitontype',
            new_name='notification',
        ),
    ]
