# Generated by Django 4.1.1 on 2022-11-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0021_rename_notificaitontype_notifications_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='notification',
            new_name='type',
        ),
    ]
